#bhpapi default config
#Wed Jun 10 12:06:49 CST 2026
validJSONOUT=c\:/temp/valid_jsonOut.txt
MedicalRecord_HPA=https\://203.65.42.199/MedicalRecord_HPA/api/CHMSSForHis//CHMSSForHis
apiUrl=https\://apcvpn.hpa.gov.tw/bhpApi/api
medRecordJSONIN=c\:/temp/medRecord_jsonIn.txt
medRecordJSONOUT=c\:/temp/medRecord_jsonOut.txt
MedicalRecord_HPA_Test=https\://60.251.1.235/MedicalRecord_HPA/api/CHMSSForHis
validJSONIN=c\:/temp/valid_jsonIn.txt
MedicalRecord_Test_Mode=true
